### ISSUE TITLE
[Feature suggestions] VWAP & trade count for binance data

### ISSUE THREAD

**Issue by petric3** [markcheno/go-quote#33]
Thank you for the great package. I'm new here and wonder if it's possible to add VWAP and trades count for bars for Binance data (possibly also other data)? This is something quite standard and very useful when it comes to bars being minute, daily, etc. Thank you :bowing_man:

**Comment by markcheno** [comment]
Thanks for the compliment! This program was designed for OHLCV data from various sources in a common format. There are 3rd party libs to calculate the VWAP that should be pretty easy to implement. See go-talib for easy to use indicators, but unfortunately it does not have VWAP because that lib was designed to exactly replicate the c/java versions of talib.
